version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_clean-arch
    environment:
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: